rollback_index=1775347200
props=com.android.build.boot.os_version:15,com.android.build.boot.fingerprint:Nothing/FroggerPro/FroggerPro:15/AQ3A.250924.001/2607231820:user/release-keys,com.android.build.boot.security_patch:2026-05-05

